// 
// Decompiled by Procyon v0.5.36
// 

package lotr.common.entity;

import java.util.LinkedHashMap;
import java.util.Collections;
import java.util.Set;
import net.minecraft.world.World;
import lotr.common.entity.item.LOTREntityGiraffeRug;
import lotr.common.entity.item.LOTREntityBearRug;
import lotr.common.entity.item.LOTREntityLionRug;
import lotr.common.entity.projectile.LOTREntityTrollSnowball;
import lotr.common.entity.item.LOTREntityArrowPoisoned;
import lotr.common.entity.projectile.LOTREntityFirePot;
import lotr.common.entity.item.LOTREntityFallingTreasure;
import lotr.common.entity.projectile.LOTREntityDart;
import lotr.common.entity.projectile.LOTREntityFishHook;
import lotr.common.entity.projectile.LOTREntityMallornLeafBomb;
import lotr.common.entity.item.LOTREntityBossTrophy;
import lotr.common.entity.projectile.LOTREntityConker;
import lotr.common.entity.projectile.LOTREntityThrownTermite;
import lotr.common.entity.item.LOTREntityBannerWall;
import lotr.common.entity.item.LOTREntityBanner;
import lotr.common.entity.item.LOTREntityBarrel;
import lotr.common.entity.projectile.LOTREntityThrownRock;
import lotr.common.entity.item.LOTREntityTraderRespawn;
import lotr.common.entity.projectile.LOTREntityMysteryWeb;
import lotr.common.entity.projectile.LOTREntityPebble;
import lotr.common.entity.item.LOTREntityStoneTroll;
import lotr.common.entity.projectile.LOTREntityCrossbowBolt;
import lotr.common.entity.projectile.LOTREntityThrowingAxe;
import lotr.common.entity.projectile.LOTREntityMarshWraithBall;
import lotr.common.entity.item.LOTREntityWargskinRug;
import lotr.common.entity.projectile.LOTREntityPlate;
import lotr.common.entity.projectile.LOTREntitySpear;
import lotr.common.entity.projectile.LOTREntityGandalfFireball;
import lotr.common.entity.item.LOTREntityOrcBomb;
import lotr.common.entity.projectile.LOTREntitySmokeRing;
import lotr.common.entity.item.LOTREntityPortal;
import lotr.common.entity.npc.LOTREntityGandalf;
import lotr.common.entity.npc.LOTREntitySaruman;
import lotr.common.entity.npc.LOTREntityGollum;
import lotr.common.entity.npc.LOTREntityUtumnoSnowTroll;
import lotr.common.entity.npc.LOTREntityUtumnoTroll;
import lotr.common.entity.npc.LOTREntityTormentedElf;
import lotr.common.entity.npc.LOTREntityBalrog;
import lotr.common.entity.npc.LOTREntityUtumnoIceSpider;
import lotr.common.entity.npc.LOTREntityUtumnoFireWarg;
import lotr.common.entity.npc.LOTREntityUtumnoObsidianWarg;
import lotr.common.entity.npc.LOTREntityUtumnoIceWarg;
import lotr.common.entity.npc.LOTREntityUtumnoWarg;
import lotr.common.entity.npc.LOTREntityUtumnoOrcArcher;
import lotr.common.entity.npc.LOTREntityUtumnoOrc;
import lotr.common.entity.npc.LOTREntityWickedDwarf;
import lotr.common.entity.npc.LOTREntityBlackUrukCaptain;
import lotr.common.entity.animal.LOTREntityWhiteOryx;
import lotr.common.entity.npc.LOTREntityTauredainSmith;
import lotr.common.entity.npc.LOTREntityGulfFarmer;
import lotr.common.entity.npc.LOTREntityUmbarFarmer;
import lotr.common.entity.npc.LOTREntitySouthronFarmer;
import lotr.common.entity.npc.LOTREntityHarnedorFarmer;
import lotr.common.entity.npc.LOTREntityHarnedorFarmhand;
import lotr.common.entity.npc.LOTREntityGulfBartender;
import lotr.common.entity.npc.LOTREntityUmbarBartender;
import lotr.common.entity.npc.LOTREntitySouthronBartender;
import lotr.common.entity.npc.LOTREntityNomadArmourer;
import lotr.common.entity.npc.LOTREntityGulfHunter;
import lotr.common.entity.npc.LOTREntityGulfLumberman;
import lotr.common.entity.npc.LOTREntityGulfGoldsmith;
import lotr.common.entity.npc.LOTREntityGulfMiner;
import lotr.common.entity.npc.LOTREntityGulfBaker;
import lotr.common.entity.npc.LOTREntityGulfFishmonger;
import lotr.common.entity.npc.LOTREntityGulfBrewer;
import lotr.common.entity.npc.LOTREntityGulfButcher;
import lotr.common.entity.npc.LOTREntityGulfMason;
import lotr.common.entity.npc.LOTREntityNomadMiner;
import lotr.common.entity.npc.LOTREntityNomadBrewer;
import lotr.common.entity.npc.LOTREntityNomadMason;
import lotr.common.entity.npc.LOTREntityUmbarMason;
import lotr.common.entity.npc.LOTREntityUmbarGoldsmith;
import lotr.common.entity.npc.LOTREntityUmbarMiner;
import lotr.common.entity.npc.LOTREntityUmbarFlorist;
import lotr.common.entity.npc.LOTREntityUmbarBaker;
import lotr.common.entity.npc.LOTREntityUmbarFishmonger;
import lotr.common.entity.npc.LOTREntityUmbarBrewer;
import lotr.common.entity.npc.LOTREntityUmbarButcher;
import lotr.common.entity.npc.LOTREntityUmbarLumberman;
import lotr.common.entity.npc.LOTREntitySouthronGoldsmith;
import lotr.common.entity.npc.LOTREntitySouthronBaker;
import lotr.common.entity.npc.LOTREntitySouthronFishmonger;
import lotr.common.entity.npc.LOTREntitySouthronMason;
import lotr.common.entity.npc.LOTREntitySouthronLumberman;
import lotr.common.entity.npc.LOTREntityHarnedorMiner;
import lotr.common.entity.npc.LOTREntityHarnedorHunter;
import lotr.common.entity.npc.LOTREntityHarnedorBaker;
import lotr.common.entity.npc.LOTREntityHarnedorFishmonger;
import lotr.common.entity.npc.LOTREntityHarnedorBrewer;
import lotr.common.entity.npc.LOTREntityHarnedorButcher;
import lotr.common.entity.npc.LOTREntityHarnedorMason;
import lotr.common.entity.npc.LOTREntityHarnedorLumberman;
import lotr.common.entity.npc.LOTREntityHarnedorBartender;
import lotr.common.entity.npc.LOTREntityNomadMerchant;
import lotr.common.entity.npc.LOTREntityGondorRenegade;
import lotr.common.entity.npc.LOTREntityGulfBlacksmith;
import lotr.common.entity.npc.LOTREntityUmbarBlacksmith;
import lotr.common.entity.npc.LOTREntityHarnedorBlacksmith;
import lotr.common.entity.npc.LOTREntityCorsairSlaver;
import lotr.common.entity.npc.LOTREntityHaradSlave;
import lotr.common.entity.npc.LOTREntitySouthronChampion;
import lotr.common.entity.npc.LOTREntityGulfHaradWarlord;
import lotr.common.entity.npc.LOTREntityNomadChieftain;
import lotr.common.entity.npc.LOTREntityCorsairCaptain;
import lotr.common.entity.npc.LOTREntityUmbarCaptain;
import lotr.common.entity.npc.LOTREntityHarnedorWarlord;
import lotr.common.entity.npc.LOTREntityNomadBannerBearer;
import lotr.common.entity.npc.LOTREntityNomadArcher;
import lotr.common.entity.npc.LOTREntityNomadWarrior;
import lotr.common.entity.npc.LOTREntityNomad;
import lotr.common.entity.npc.LOTREntityCorsair;
import lotr.common.entity.npc.LOTREntityGulfHaradBannerBearer;
import lotr.common.entity.npc.LOTREntityGulfHaradArcher;
import lotr.common.entity.npc.LOTREntityGulfHaradWarrior;
import lotr.common.entity.npc.LOTREntityGulfHaradrim;
import lotr.common.entity.npc.LOTREntityMoredainMercenary;
import lotr.common.entity.npc.LOTREntityUmbarBannerBearer;
import lotr.common.entity.npc.LOTREntityUmbarArcher;
import lotr.common.entity.npc.LOTREntityUmbarWarrior;
import lotr.common.entity.npc.LOTREntityUmbarian;
import lotr.common.entity.npc.LOTREntityHarnedorBannerBearer;
import lotr.common.entity.npc.LOTREntityHarnedorArcher;
import lotr.common.entity.npc.LOTREntityHarnedorWarrior;
import lotr.common.entity.npc.LOTREntityHarnedhrim;
import lotr.common.entity.npc.LOTREntitySnowTroll;
import lotr.common.entity.npc.LOTREntityNearHaradBlacksmith;
import lotr.common.entity.npc.LOTREntityGundabadOrcTrader;
import lotr.common.entity.animal.LOTREntityFish;
import lotr.common.entity.npc.LOTREntityRivendellTrader;
import lotr.common.entity.npc.LOTREntityEsgarothBannerBearer;
import lotr.common.entity.npc.LOTREntityRivendellSmith;
import lotr.common.entity.npc.LOTREntityRivendellBannerBearer;
import lotr.common.entity.npc.LOTREntityRivendellLord;
import lotr.common.entity.npc.LOTREntityRivendellWarrior;
import lotr.common.entity.npc.LOTREntityRivendellElf;
import lotr.common.entity.npc.LOTREntityEasterlingFarmhand;
import lotr.common.entity.npc.LOTREntityDorwinionElfArcher;
import lotr.common.entity.npc.LOTREntityEasterlingBartender;
import lotr.common.entity.npc.LOTREntityEasterlingGoldsmith;
import lotr.common.entity.npc.LOTREntityEasterlingFarmer;
import lotr.common.entity.npc.LOTREntityEasterlingHunter;
import lotr.common.entity.npc.LOTREntityEasterlingBaker;
import lotr.common.entity.npc.LOTREntityEasterlingFishmonger;
import lotr.common.entity.npc.LOTREntityEasterlingBrewer;
import lotr.common.entity.npc.LOTREntityEasterlingButcher;
import lotr.common.entity.npc.LOTREntityEasterlingMason;
import lotr.common.entity.npc.LOTREntityEasterlingLumberman;
import lotr.common.entity.npc.LOTREntityEasterlingGoldWarrior;
import lotr.common.entity.npc.LOTREntityDorwinionMerchantMan;
import lotr.common.entity.npc.LOTREntityEasterlingLevyman;
import lotr.common.entity.npc.LOTREntityEasterlingFireThrower;
import lotr.common.entity.npc.LOTREntityEasterlingWarlord;
import lotr.common.entity.npc.LOTREntityEasterlingBlacksmith;
import lotr.common.entity.npc.LOTREntityEasterlingArcher;
import lotr.common.entity.npc.LOTREntityEasterlingBannerBearer;
import lotr.common.entity.npc.LOTREntityEasterlingWarrior;
import lotr.common.entity.npc.LOTREntityEasterling;
import lotr.common.entity.animal.LOTREntityBear;
import lotr.common.entity.npc.LOTREntityRohanStablemaster;
import lotr.common.entity.npc.LOTREntityDunedainBlacksmith;
import lotr.common.entity.npc.LOTREntityRohanOrcharder;
import lotr.common.entity.npc.LOTREntityRohanBaker;
import lotr.common.entity.npc.LOTREntityRohanFishmonger;
import lotr.common.entity.npc.LOTREntityRohanButcher;
import lotr.common.entity.npc.LOTREntityRohanBrewer;
import lotr.common.entity.npc.LOTREntityRohanBuilder;
import lotr.common.entity.npc.LOTREntityRohanLumberman;
import lotr.common.entity.npc.LOTREntityRohanFarmer;
import lotr.common.entity.animal.LOTREntitySeagull;
import lotr.common.entity.animal.LOTREntityGorcrow;
import lotr.common.entity.npc.LOTREntityRohanFarmhand;
import lotr.common.entity.npc.LOTREntityLamedonHillman;
import lotr.common.entity.npc.LOTREntityLamedonCaptain;
import lotr.common.entity.npc.LOTREntityLamedonBannerBearer;
import lotr.common.entity.npc.LOTREntityLamedonArcher;
import lotr.common.entity.npc.LOTREntityLamedonSoldier;
import lotr.common.entity.npc.LOTREntityLebenninCaptain;
import lotr.common.entity.npc.LOTREntityBlackrootCaptain;
import lotr.common.entity.npc.LOTREntityPinnathGelinCaptain;
import lotr.common.entity.npc.LOTREntityPelargirCaptain;
import lotr.common.entity.npc.LOTREntityLossarnachCaptain;
import lotr.common.entity.npc.LOTREntityGondorBaker;
import lotr.common.entity.npc.LOTREntityGondorFishmonger;
import lotr.common.entity.npc.LOTREntityGondorButcher;
import lotr.common.entity.npc.LOTREntityGondorFlorist;
import lotr.common.entity.npc.LOTREntityGondorBrewer;
import lotr.common.entity.npc.LOTREntityGondorMason;
import lotr.common.entity.npc.LOTREntityGondorLumberman;
import lotr.common.entity.npc.LOTREntityGondorGreengrocer;
import lotr.common.entity.npc.LOTREntityGondorBartender;
import lotr.common.entity.npc.LOTREntityLebenninBannerBearer;
import lotr.common.entity.npc.LOTREntityLebenninLevyman;
import lotr.common.entity.npc.LOTREntityGondorFarmhand;
import lotr.common.entity.npc.LOTREntityGondorFarmer;
import lotr.common.entity.npc.LOTREntityDolAmrothArcher;
import lotr.common.entity.npc.LOTREntityDolAmrothSoldier;
import lotr.common.entity.npc.LOTREntityMinasMorgulBannerBearer;
import lotr.common.entity.npc.LOTREntityNanUngolBannerBearer;
import lotr.common.entity.npc.LOTREntityGondorLevyman;
import lotr.common.entity.npc.LOTREntityBlackrootArcher;
import lotr.common.entity.npc.LOTREntityBlackrootBannerBearer;
import lotr.common.entity.npc.LOTREntityBlackrootSoldier;
import lotr.common.entity.npc.LOTREntityPinnathGelinBannerBearer;
import lotr.common.entity.npc.LOTREntityPinnathGelinSoldier;
import lotr.common.entity.npc.LOTREntityPelargirBannerBearer;
import lotr.common.entity.npc.LOTREntityPelargirMarine;
import lotr.common.entity.npc.LOTREntityBlackUrukBannerBearer;
import lotr.common.entity.npc.LOTREntityLossarnachBannerBearer;
import lotr.common.entity.npc.LOTREntityLossarnachAxeman;
import lotr.common.entity.npc.LOTREntityDorwinionCrossbower;
import lotr.common.entity.animal.LOTREntityKineAraw;
import lotr.common.entity.animal.LOTREntityAurochs;
import lotr.common.entity.npc.LOTREntityDaleMerchant;
import lotr.common.entity.npc.LOTREntityDorwinionMerchantElf;
import lotr.common.entity.npc.LOTREntityDorwinionVinekeeper;
import lotr.common.entity.npc.LOTREntityDorwinionVinehand;
import lotr.common.entity.npc.LOTREntityDorwinionElfVintner;
import lotr.common.entity.npc.LOTREntityDaleBaker;
import lotr.common.entity.npc.LOTREntityDorwinionElfCaptain;
import lotr.common.entity.npc.LOTREntityDorwinionElfBannerBearer;
import lotr.common.entity.npc.LOTREntityDorwinionElfWarrior;
import lotr.common.entity.npc.LOTREntityDorwinionElf;
import lotr.common.entity.npc.LOTREntityDorwinionBannerBearer;
import lotr.common.entity.npc.LOTREntityDorwinionCaptain;
import lotr.common.entity.npc.LOTREntityDorwinionGuard;
import lotr.common.entity.npc.LOTREntityDorwinionMan;
import lotr.common.entity.npc.LOTREntityDaleBlacksmith;
import lotr.common.entity.npc.LOTREntityDaleCaptain;
import lotr.common.entity.npc.LOTREntityDaleBannerBearer;
import lotr.common.entity.npc.LOTREntityDaleArcher;
import lotr.common.entity.npc.LOTREntityDaleSoldier;
import lotr.common.entity.npc.LOTREntityDaleLevyman;
import lotr.common.entity.npc.LOTREntityDaleMan;
import lotr.common.entity.animal.LOTREntityDeer;
import lotr.common.entity.npc.LOTREntityBanditHarad;
import lotr.common.entity.npc.LOTREntityIsengardSnagaArcher;
import lotr.common.entity.npc.LOTREntityIsengardSnaga;
import lotr.common.entity.npc.LOTREntityGundabadUrukArcher;
import lotr.common.entity.npc.LOTREntityGundabadUruk;
import lotr.common.entity.npc.LOTREntityTauredainPyramidWraith;
import lotr.common.entity.npc.LOTREntityBlueMountainsSmith;
import lotr.common.entity.npc.LOTREntityDwarfSmith;
import lotr.common.entity.npc.LOTREntityTauredainFarmhand;
import lotr.common.entity.npc.LOTREntityTauredainFarmer;
import lotr.common.entity.npc.LOTREntityGaladhrimWarden;
import lotr.common.entity.npc.LOTREntityTauredainShaman;
import lotr.common.entity.npc.LOTREntityBarrowWight;
import lotr.common.entity.npc.LOTREntityTauredainBlowgunner;
import lotr.common.entity.npc.LOTREntityTauredainChieftain;
import lotr.common.entity.npc.LOTREntityTauredainBannerBearer;
import lotr.common.entity.npc.LOTREntityTauredainWarrior;
import lotr.common.entity.npc.LOTREntityTauredain;
import lotr.common.entity.npc.LOTREntityScrapTrader;
import lotr.common.entity.npc.LOTREntityMallornEnt;
import lotr.common.entity.npc.LOTREntityIronHillsMerchant;
import lotr.common.entity.npc.LOTREntityDunlendingAxeThrower;
import lotr.common.entity.npc.LOTREntityAngmarHillmanAxeThrower;
import lotr.common.entity.npc.LOTREntityAngmarHillmanBannerBearer;
import lotr.common.entity.npc.LOTREntityAngmarHillmanChieftain;
import lotr.common.entity.npc.LOTREntityAngmarHillmanWarrior;
import lotr.common.entity.npc.LOTREntityAngmarHillman;
import lotr.common.entity.npc.LOTREntityDunlendingBerserker;
import lotr.common.entity.npc.LOTREntityMoredainHutmaker;
import lotr.common.entity.npc.LOTREntityMoredainHuntsman;
import lotr.common.entity.npc.LOTREntityMoredainChieftain;
import lotr.common.entity.npc.LOTREntityMoredainBannerBearer;
import lotr.common.entity.npc.LOTREntityMoredainWarrior;
import lotr.common.entity.npc.LOTREntityMoredain;
import lotr.common.entity.animal.LOTREntitySwan;
import lotr.common.entity.npc.LOTREntityDolAmrothBannerBearer;
import lotr.common.entity.npc.LOTREntityDolAmrothCaptain;
import lotr.common.entity.npc.LOTREntitySwanKnight;
import lotr.common.entity.npc.LOTREntityWoodElfSmith;
import lotr.common.entity.npc.LOTREntityHighElfSmith;
import lotr.common.entity.npc.LOTREntityGaladhrimSmith;
import lotr.common.entity.npc.LOTREntityHalfTrollScavenger;
import lotr.common.entity.npc.LOTREntityDolGuldurOrcTrader;
import lotr.common.entity.npc.LOTREntityAngmarOrcTrader;
import lotr.common.entity.npc.LOTREntityHalfTrollWarlord;
import lotr.common.entity.npc.LOTREntityHalfTrollBannerBearer;
import lotr.common.entity.npc.LOTREntityHalfTrollWarrior;
import lotr.common.entity.npc.LOTREntityRangerIthilienBannerBearer;
import lotr.common.entity.npc.LOTREntityRangerIthilienCaptain;
import lotr.common.entity.npc.LOTREntityHalfTroll;
import lotr.common.entity.npc.LOTREntityBlackUrukArcher;
import lotr.common.entity.npc.LOTREntityBlackUruk;
import lotr.common.entity.animal.LOTREntityDikDik;
import lotr.common.entity.animal.LOTREntityTermite;
import lotr.common.entity.npc.LOTREntityGundabadBannerBearer;
import lotr.common.entity.npc.LOTREntityMirkTroll;
import lotr.common.entity.npc.LOTREntityDolGuldurOrcChieftain;
import lotr.common.entity.npc.LOTREntityDolGuldurBannerBearer;
import lotr.common.entity.npc.LOTREntityDolGuldurOrcArcher;
import lotr.common.entity.npc.LOTREntityDolGuldurOrc;
import lotr.common.entity.npc.LOTREntityHaradPyramidWraith;
import lotr.common.entity.npc.LOTREntityNearHaradMerchant;
import lotr.common.entity.npc.LOTREntityGondorTowerGuard;
import lotr.common.entity.animal.LOTREntityElk;
import lotr.common.entity.npc.LOTREntityRangerNorthBannerBearer;
import lotr.common.entity.npc.LOTREntityBandit;
import lotr.common.entity.npc.LOTREntityBlueDwarfMerchant;
import lotr.common.entity.npc.LOTREntitySouthronButcher;
import lotr.common.entity.npc.LOTREntitySouthronFlorist;
import lotr.common.entity.npc.LOTREntitySouthronMiner;
import lotr.common.entity.npc.LOTREntitySouthronBrewer;
import lotr.common.entity.npc.LOTREntityBlueDwarfMiner;
import lotr.common.entity.npc.LOTREntityBlueDwarfCommander;
import lotr.common.entity.npc.LOTREntityBlueDwarfBannerBearer;
import lotr.common.entity.npc.LOTREntityBlueDwarfAxeThrower;
import lotr.common.entity.npc.LOTREntityBlueDwarfWarrior;
import lotr.common.entity.npc.LOTREntityBlueDwarf;
import lotr.common.entity.npc.LOTREntityNearHaradrimWarlord;
import lotr.common.entity.npc.LOTREntityNearHaradrimArcher;
import lotr.common.entity.animal.LOTREntityCamel;
import lotr.common.entity.animal.LOTREntityCrebain;
import lotr.common.entity.animal.LOTREntityBird;
import lotr.common.entity.animal.LOTREntityDesertScorpion;
import lotr.common.entity.animal.LOTREntityJungleScorpion;
import lotr.common.entity.npc.LOTREntityHighElfBannerBearer;
import lotr.common.entity.npc.LOTREntityNearHaradBannerBearer;
import lotr.common.entity.npc.LOTREntityAngmarBannerBearer;
import lotr.common.entity.npc.LOTREntityDwarfBannerBearer;
import lotr.common.entity.npc.LOTREntityUrukHaiBannerBearer;
import lotr.common.entity.npc.LOTREntityDunlendingBannerBearer;
import lotr.common.entity.npc.LOTREntityWoodElfBannerBearer;
import lotr.common.entity.npc.LOTREntityGaladhrimBannerBearer;
import lotr.common.entity.npc.LOTREntityMordorBannerBearer;
import lotr.common.entity.npc.LOTREntityRohanBannerBearer;
import lotr.common.entity.npc.LOTREntityGondorBannerBearer;
import lotr.common.entity.npc.LOTREntityHighElfLord;
import lotr.common.entity.npc.LOTREntityHighElfWarrior;
import lotr.common.entity.npc.LOTREntityHobbitFarmhand;
import lotr.common.entity.npc.LOTREntityHobbitFarmer;
import lotr.common.entity.animal.LOTREntityFlamingo;
import lotr.common.entity.animal.LOTREntityGemsbok;
import lotr.common.entity.npc.LOTREntityHighElf;
import lotr.common.entity.npc.LOTREntityNearHaradrimWarrior;
import lotr.common.entity.npc.LOTREntityNearHaradrim;
import lotr.common.entity.animal.LOTREntityCrocodile;
import lotr.common.entity.animal.LOTREntityRhino;
import lotr.common.entity.animal.LOTREntityZebra;
import lotr.common.entity.animal.LOTREntityGiraffe;
import lotr.common.entity.animal.LOTREntityLioness;
import lotr.common.entity.animal.LOTREntityLion;
import lotr.common.entity.npc.LOTREntityUrukWargBombardier;
import lotr.common.entity.npc.LOTREntityUrukWarg;
import lotr.common.entity.npc.LOTREntityAngmarWargBombardier;
import lotr.common.entity.npc.LOTREntityAngmarWarg;
import lotr.common.entity.npc.LOTREntityGundabadWarg;
import lotr.common.entity.npc.LOTREntityRangerNorthCaptain;
import lotr.common.entity.npc.LOTREntityGundabadOrcMercenaryCaptain;
import lotr.common.entity.npc.LOTREntityGundabadOrcArcher;
import lotr.common.entity.npc.LOTREntityGundabadOrc;
import lotr.common.entity.npc.LOTREntityAngmarOrcBombardier;
import lotr.common.entity.npc.LOTREntityAngmarOrcArcher;
import lotr.common.entity.npc.LOTREntityAngmarOrc;
import lotr.common.entity.npc.LOTREntityMordorOrcSpiderKeeper;
import lotr.common.entity.npc.LOTREntityMordorSpider;
import lotr.common.entity.npc.LOTREntityMordorOrcSlaver;
import lotr.common.entity.npc.LOTREntityHobbitOrcharder;
import lotr.common.entity.animal.LOTREntityWildBoar;
import lotr.common.entity.animal.LOTREntityRabbit;
import lotr.common.entity.npc.LOTREntityNurnSlave;
import lotr.common.entity.npc.LOTREntityDunedain;
import lotr.common.entity.npc.LOTREntityAngmarOrcMercenaryCaptain;
import lotr.common.entity.animal.LOTREntityMidges;
import lotr.common.entity.animal.LOTREntityButterfly;
import lotr.common.entity.npc.LOTREntityRohanMeadhost;
import lotr.common.entity.npc.LOTREntityWoodElfCaptain;
import lotr.common.entity.npc.LOTREntityWoodElfWarrior;
import lotr.common.entity.npc.LOTREntityDarkHuorn;
import lotr.common.entity.npc.LOTREntityHuorn;
import lotr.common.entity.npc.LOTREntityMountainTrollChieftain;
import lotr.common.entity.npc.LOTREntityMountainTroll;
import lotr.common.entity.npc.LOTREntityEnt;
import lotr.common.entity.npc.LOTREntityRohanShieldmaiden;
import lotr.common.entity.npc.LOTREntityDunlendingBartender;
import lotr.common.entity.npc.LOTREntityDunlending;
import lotr.common.entity.npc.LOTREntityDunlendingWarlord;
import lotr.common.entity.npc.LOTREntityDunlendingArcher;
import lotr.common.entity.npc.LOTREntityDunlendingWarrior;
import lotr.common.entity.npc.LOTREntityRangerIthilien;
import lotr.common.entity.npc.LOTREntityRangerNorth;
import lotr.common.entity.npc.LOTREntityRohanBlacksmith;
import lotr.common.entity.npc.LOTREntityHobbitShirriffChief;
import lotr.common.entity.npc.LOTREntityHobbitShirriff;
import lotr.common.entity.npc.LOTREntityRohirrimMarshal;
import lotr.common.entity.npc.LOTREntityRohirrimArcher;
import lotr.common.entity.npc.LOTREntityRohirrimWarrior;
import lotr.common.entity.npc.LOTREntityRohanBarrowWraith;
import lotr.common.entity.npc.LOTREntityWoodElfScout;
import lotr.common.entity.npc.LOTREntityWoodElf;
import lotr.common.entity.npc.LOTREntityMirkwoodSpider;
import lotr.common.entity.npc.LOTREntityUrukHaiSapper;
import lotr.common.entity.npc.LOTREntityGaladhrimLord;
import lotr.common.entity.npc.LOTREntityOlogHai;
import lotr.common.entity.npc.LOTREntityTroll;
import lotr.common.entity.npc.LOTREntityUrukHaiMercenaryCaptain;
import lotr.common.entity.npc.LOTREntityUrukHaiTrader;
import lotr.common.entity.npc.LOTREntityUrukHaiBerserker;
import lotr.common.entity.npc.LOTREntityUrukHaiCrossbower;
import lotr.common.entity.npc.LOTREntityUrukHai;
import lotr.common.entity.npc.LOTREntityGondorArcher;
import lotr.common.entity.npc.LOTREntityDwarfAxeThrower;
import lotr.common.entity.npc.LOTREntityDwarfCommander;
import lotr.common.entity.npc.LOTREntityGondorianCaptain;
import lotr.common.entity.npc.LOTREntityMordorOrcMercenaryCaptain;
import lotr.common.entity.npc.LOTREntityMordorWargBombardier;
import lotr.common.entity.npc.LOTREntityMarshWraith;
import lotr.common.entity.npc.LOTREntityDwarfMiner;
import lotr.common.entity.npc.LOTREntityDwarfWarrior;
import lotr.common.entity.npc.LOTREntityDwarf;
import lotr.common.entity.npc.LOTREntityGaladhrimTrader;
import lotr.common.entity.npc.LOTREntityGondorBlacksmith;
import lotr.common.entity.npc.LOTREntityGondorRuinsWraith;
import lotr.common.entity.npc.LOTREntityMordorOrcArcher;
import lotr.common.entity.npc.LOTREntityMordorOrcTrader;
import lotr.common.entity.npc.LOTREntityMordorOrcBombardier;
import lotr.common.entity.npc.LOTREntityGaladhrimWarrior;
import lotr.common.entity.npc.LOTREntityRohanMan;
import lotr.common.entity.npc.LOTREntityHobbitBartender;
import lotr.common.entity.npc.LOTREntityGaladhrimElf;
import lotr.common.entity.npc.LOTREntityGondorMan;
import lotr.common.entity.npc.LOTREntityGondorSoldier;
import lotr.common.entity.npc.LOTREntityMordorWarg;
import lotr.common.entity.animal.LOTREntityShirePony;
import lotr.common.entity.npc.LOTREntityMordorOrc;
import lotr.common.entity.npc.LOTREntityHobbit;
import lotr.common.entity.animal.LOTREntityHorse;
import net.minecraft.entity.EntityList;
import cpw.mods.fml.common.registry.EntityRegistry;
import lotr.common.LOTRMod;
import net.minecraft.entity.Entity;
import java.util.Map;
import java.util.HashMap;

public class LOTREntities
{
    public static HashMap<Integer, SpawnEggInfo> spawnEggs;
    public static Map<String, Integer> stringToIDMapping;
    public static Map<Integer, String> IDToStringMapping;
    public static Map<Class<? extends Entity>, Integer> classToIDMapping;
    
    public static void registerCreature(final Class<? extends Entity> entityClass, final String name, final int id, final int eggBackground, final int eggSpots) {
        registerEntity(entityClass, name, id, 80, 3, true);
        LOTREntities.spawnEggs.put(id, new SpawnEggInfo(id, eggBackground, eggSpots));
    }
    
    public static void registerCreature(final Class<? extends Entity> entityClass, final String name, final int id) {
        registerEntity(entityClass, name, id, 80, 3, true);
    }
    
    public static void registerEntity(final Class<? extends Entity> entityClass, final String name, final int id, final int updateRange, final int updateFreq, final boolean sendVelocityUpdates) {
        EntityRegistry.registerModEntity((Class)entityClass, name, id, (Object)LOTRMod.instance, updateRange, updateFreq, sendVelocityUpdates);
        final String fullName = EntityList.classToStringMapping.get(entityClass);
        LOTREntities.stringToIDMapping.put(fullName, id);
        LOTREntities.IDToStringMapping.put(id, fullName);
        LOTREntities.classToIDMapping.put(entityClass, id);
    }
    
    public static void registerEntities() {
        registerCreature((Class<? extends Entity>)LOTREntityHorse.class, "Horse", 1, 8601889, 4136462);
        registerCreature((Class<? extends Entity>)LOTREntityHobbit.class, "Hobbit", 2, 16752511, 8010275);
        registerCreature((Class<? extends Entity>)LOTREntityMordorOrc.class, "MordorOrc", 3, 3353378, 7042407);
        registerCreature((Class<? extends Entity>)LOTREntityShirePony.class, "ShirePony", 4, 6109994, 13017995);
        registerCreature((Class<? extends Entity>)LOTREntityMordorWarg.class, "MordorWarg", 5, 4600617, 2694422);
        registerCreature((Class<? extends Entity>)LOTREntityGondorSoldier.class, "GondorSoldier", 6, 5327948, 15063770);
        registerCreature((Class<? extends Entity>)LOTREntityGondorMan.class, "GondorMan", 7, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityGaladhrimElf.class, "GaladhrimElf", 8, 9337185, 15920555);
        registerCreature((Class<? extends Entity>)LOTREntityHobbitBartender.class, "HobbitBartender", 9, 16752511, 8010275);
        registerCreature((Class<? extends Entity>)LOTREntityRohanMan.class, "RohanMan", 10, 16424833, 13406801);
        registerCreature((Class<? extends Entity>)LOTREntityGaladhrimWarrior.class, "GaladhrimWarrior", 11, 12697274, 15382870);
        registerCreature((Class<? extends Entity>)LOTREntityMordorOrcBombardier.class, "MordorOrcBombardier", 12, 3353378, 7042407);
        registerCreature((Class<? extends Entity>)LOTREntityMordorOrcTrader.class, "MordorOrcTrader", 13, 5979436, 13421772);
        registerCreature((Class<? extends Entity>)LOTREntityMordorOrcArcher.class, "MordorOrcArcher", 14, 3353378, 7042407);
        registerCreature((Class<? extends Entity>)LOTREntityGondorRuinsWraith.class, "GondorRuinsWraith", 15, 12698049, 4802889);
        registerCreature((Class<? extends Entity>)LOTREntityGondorBlacksmith.class, "GondorBlacksmith", 16, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityGaladhrimTrader.class, "GaladhrimTrader", 17, 2047778, 16762150);
        registerCreature((Class<? extends Entity>)LOTREntityDwarf.class, "Dwarf", 18, 16353133, 15357472);
        registerCreature((Class<? extends Entity>)LOTREntityDwarfWarrior.class, "DwarfWarrior", 19, 2238506, 7108730);
        registerCreature((Class<? extends Entity>)LOTREntityDwarfMiner.class, "DwarfMiner", 20, 16353133, 15357472);
        registerCreature((Class<? extends Entity>)LOTREntityMarshWraith.class, "MarshWraith", 21, 10524036, 6179636);
        registerCreature((Class<? extends Entity>)LOTREntityMordorWargBombardier.class, "MordorWargBombardier", 22, 4600617, 2694422);
        registerCreature((Class<? extends Entity>)LOTREntityMordorOrcMercenaryCaptain.class, "MordorOrcMercenaryCaptain", 23, 3353378, 7042407);
        registerCreature((Class<? extends Entity>)LOTREntityGondorianCaptain.class, "GondorianCaptain", 24, 5327948, 15063770);
        registerCreature((Class<? extends Entity>)LOTREntityDwarfCommander.class, "DwarfCommander", 25, 2238506, 7108730);
        registerCreature((Class<? extends Entity>)LOTREntityDwarfAxeThrower.class, "DwarfAxeThrower", 26, 2238506, 7108730);
        registerCreature((Class<? extends Entity>)LOTREntityGondorArcher.class, "GondorArcher", 27, 5327948, 15063770);
        registerCreature((Class<? extends Entity>)LOTREntityUrukHai.class, "UrukHai", 28, 2369050, 5790015);
        registerCreature((Class<? extends Entity>)LOTREntityUrukHaiCrossbower.class, "UrukHaiCrossbower", 29, 2369050, 5790015);
        registerCreature((Class<? extends Entity>)LOTREntityUrukHaiBerserker.class, "UrukHaiBerserker", 30, 2369050, 14408662);
        registerCreature((Class<? extends Entity>)LOTREntityUrukHaiTrader.class, "UrukHaiTrader", 31, 5979436, 13421772);
        registerCreature((Class<? extends Entity>)LOTREntityUrukHaiMercenaryCaptain.class, "UrukHaiMercenaryCaptain", 32, 2369050, 5790015);
        registerCreature((Class<? extends Entity>)LOTREntityTroll.class, "Troll", 33, 10848082, 4796702);
        registerCreature((Class<? extends Entity>)LOTREntityOlogHai.class, "OlogHai", 34, 4147260, 2237218);
        registerCreature((Class<? extends Entity>)LOTREntityGaladhrimLord.class, "GaladhrimLord", 35, 12697274, 15382870);
        registerCreature((Class<? extends Entity>)LOTREntityUrukHaiSapper.class, "UrukHaiSapper", 36, 2369050, 5790015);
        registerCreature((Class<? extends Entity>)LOTREntityMirkwoodSpider.class, "MirkwoodSpider", 37, 2630945, 1315088);
        registerCreature((Class<? extends Entity>)LOTREntityWoodElf.class, "WoodElf", 38, 2314529, 16764574);
        registerCreature((Class<? extends Entity>)LOTREntityWoodElfScout.class, "WoodElfScout", 39, 336140, 3891251);
        registerCreature((Class<? extends Entity>)LOTREntityRohanBarrowWraith.class, "RohanBarrowWraith", 40, 12698049, 4802889);
        registerCreature((Class<? extends Entity>)LOTREntityRohirrimWarrior.class, "Rohirrim", 41, 5524296, 13546384);
        registerCreature((Class<? extends Entity>)LOTREntityRohirrimArcher.class, "RohirrimArcher", 42, 5524296, 13546384);
        registerCreature((Class<? extends Entity>)LOTREntityRohirrimMarshal.class, "RohirrimMarshal", 43, 6180940, 14857848);
        registerCreature((Class<? extends Entity>)LOTREntityHobbitShirriff.class, "HobbitShirriff", 44, 16752511, 8010275);
        registerCreature((Class<? extends Entity>)LOTREntityHobbitShirriffChief.class, "HobbitShirriffChief", 45, 16752511, 8010275);
        registerCreature((Class<? extends Entity>)LOTREntityRohanBlacksmith.class, "RohanBlacksmith", 46, 16424833, 13406801);
        registerCreature((Class<? extends Entity>)LOTREntityRangerNorth.class, "RangerNorth", 47, 4473912, 2302748);
        registerCreature((Class<? extends Entity>)LOTREntityRangerIthilien.class, "RangerIthilien", 48, 4015141, 1382669);
        registerCreature((Class<? extends Entity>)LOTREntityDunlendingWarrior.class, "DunlendingWarrior", 49, 5192753, 9337975);
        registerCreature((Class<? extends Entity>)LOTREntityDunlendingArcher.class, "DunlendingArcher", 50, 5192753, 9337975);
        registerCreature((Class<? extends Entity>)LOTREntityDunlendingWarlord.class, "DunlendingWarlord", 51, 5192753, 9337975);
        registerCreature((Class<? extends Entity>)LOTREntityDunlending.class, "Dunlending", 52, 15897714, 3679258);
        registerCreature((Class<? extends Entity>)LOTREntityDunlendingBartender.class, "DunlendingBartender", 53, 15897714, 3679258);
        registerCreature((Class<? extends Entity>)LOTREntityRohanShieldmaiden.class, "RohanShieldmaiden", 54, 5524296, 13546384);
        registerCreature((Class<? extends Entity>)LOTREntityEnt.class, "Ent", 55, 3681048, 6788650);
        registerCreature((Class<? extends Entity>)LOTREntityMountainTroll.class, "MountainTroll", 56, 9991001, 5651753);
        registerCreature((Class<? extends Entity>)LOTREntityMountainTrollChieftain.class, "MountainTrollChieftain", 57);
        registerCreature((Class<? extends Entity>)LOTREntityHuorn.class, "Huorn", 58, 3681048, 6788650);
        registerCreature((Class<? extends Entity>)LOTREntityDarkHuorn.class, "DarkHuorn", 59, 2498067, 2643485);
        registerCreature((Class<? extends Entity>)LOTREntityWoodElfWarrior.class, "WoodElfWarrior", 60, 12231576, 5856300);
        registerCreature((Class<? extends Entity>)LOTREntityWoodElfCaptain.class, "WoodElfCaptain", 61, 12231576, 5856300);
        registerCreature((Class<? extends Entity>)LOTREntityRohanMeadhost.class, "RohanMeadhost", 62, 6567206, 14392402);
        registerCreature((Class<? extends Entity>)LOTREntityButterfly.class, "Butterfly", 63, 2498589, 16747542);
        registerCreature((Class<? extends Entity>)LOTREntityMidges.class, "Midges", 64, 5653040, 1972242);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarOrcMercenaryCaptain.class, "AngmarOrcMercenaryCaptain", 65, 3224873, 5601097);
        registerCreature((Class<? extends Entity>)LOTREntityDunedain.class, "Dunedain", 66, 15638664, 6832694);
        registerCreature((Class<? extends Entity>)LOTREntityNurnSlave.class, "NurnSlave", 67, 8613981, 4864555);
        registerCreature((Class<? extends Entity>)LOTREntityRabbit.class, "Rabbit", 68, 9860178, 5520938);
        registerCreature((Class<? extends Entity>)LOTREntityWildBoar.class, "Boar", 69, 6635562, 4069378);
        registerCreature((Class<? extends Entity>)LOTREntityHobbitOrcharder.class, "HobbitOrcharder", 70, 16752511, 8010275);
        registerCreature((Class<? extends Entity>)LOTREntityMordorOrcSlaver.class, "MordorOrcSlaver", 71, 3353378, 7042407);
        registerCreature((Class<? extends Entity>)LOTREntityMordorSpider.class, "MordorSpider", 72, 1511181, 12917534);
        registerCreature((Class<? extends Entity>)LOTREntityMordorOrcSpiderKeeper.class, "MordorOrcSpiderKeeper", 73, 3353378, 7042407);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarOrc.class, "AngmarOrc", 74, 3224873, 5601097);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarOrcArcher.class, "AngmarOrcArcher", 75, 3224873, 5601097);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarOrcBombardier.class, "AngmarOrcBombardier", 76, 3224873, 5601097);
        registerCreature((Class<? extends Entity>)LOTREntityGundabadOrc.class, "GundabadOrc", 77, 3352346, 8548435);
        registerCreature((Class<? extends Entity>)LOTREntityGundabadOrcArcher.class, "GundabadOrcArcher", 78, 3352346, 8548435);
        registerCreature((Class<? extends Entity>)LOTREntityGundabadOrcMercenaryCaptain.class, "GundabadOrcMercenaryCaptain", 79, 2563350, 6382678);
        registerCreature((Class<? extends Entity>)LOTREntityRangerNorthCaptain.class, "RangerNorthCaptain", 80, 4473912, 2302748);
        registerCreature((Class<? extends Entity>)LOTREntityGundabadWarg.class, "GundabadWarg", 81, 4600617, 2694422);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarWarg.class, "AngmarWarg", 82, 4600617, 2694422);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarWargBombardier.class, "AngmarWargBombardier", 83, 4600617, 2694422);
        registerCreature((Class<? extends Entity>)LOTREntityUrukWarg.class, "UrukWarg", 84, 4600617, 2694422);
        registerCreature((Class<? extends Entity>)LOTREntityUrukWargBombardier.class, "UrukWargBombardier", 85, 4600617, 2694422);
        registerCreature((Class<? extends Entity>)LOTREntityLion.class, "Lion", 86, 13345354, 10838576);
        registerCreature((Class<? extends Entity>)LOTREntityLioness.class, "Lioness", 87, 13346908, 11238466);
        registerCreature((Class<? extends Entity>)LOTREntityGiraffe.class, "Giraffe", 88, 13608551, 6966048);
        registerCreature((Class<? extends Entity>)LOTREntityZebra.class, "Zebra", 89, 15000804, 4340020);
        registerCreature((Class<? extends Entity>)LOTREntityRhino.class, "Rhino", 90, 6118481, 12171165);
        registerCreature((Class<? extends Entity>)LOTREntityCrocodile.class, "Crocodile", 91, 2896659, 986886);
        registerCreature((Class<? extends Entity>)LOTREntityNearHaradrim.class, "NearHaradrim", 92, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityNearHaradrimWarrior.class, "NearHaradrimWarrior", 93, 2171169, 11868955);
        registerCreature((Class<? extends Entity>)LOTREntityHighElf.class, "HighElf", 94, 16761223, 15721387);
        registerCreature((Class<? extends Entity>)LOTREntityGemsbok.class, "Gemsbok", 95, 11759423, 15920343);
        registerCreature((Class<? extends Entity>)LOTREntityFlamingo.class, "Flamingo", 96, 16087966, 16374243);
        registerCreature((Class<? extends Entity>)LOTREntityHobbitFarmer.class, "HobbitFarmer", 97, 16752511, 8010275);
        registerCreature((Class<? extends Entity>)LOTREntityHobbitFarmhand.class, "HobbitFarmhand", 98, 16752511, 8010275);
        registerCreature((Class<? extends Entity>)LOTREntityHighElfWarrior.class, "HighElfWarrior", 99, 14935016, 7040410);
        registerCreature((Class<? extends Entity>)LOTREntityHighElfLord.class, "HighElfLord", 100, 14935016, 7040410);
        registerCreature((Class<? extends Entity>)LOTREntityGondorBannerBearer.class, "GondorBannerBearer", 101, 5327948, 15063770);
        registerCreature((Class<? extends Entity>)LOTREntityRohanBannerBearer.class, "RohanBannerBearer", 102, 5524296, 13546384);
        registerCreature((Class<? extends Entity>)LOTREntityMordorBannerBearer.class, "MordorBannerBearer", 103, 3353378, 7042407);
        registerCreature((Class<? extends Entity>)LOTREntityGaladhrimBannerBearer.class, "GaladhrimBannerBearer", 104, 12697274, 15382870);
        registerCreature((Class<? extends Entity>)LOTREntityWoodElfBannerBearer.class, "WoodElfBannerBearer", 105, 12231576, 5856300);
        registerCreature((Class<? extends Entity>)LOTREntityDunlendingBannerBearer.class, "DunlendingBannerBearer", 106, 5192753, 9337975);
        registerCreature((Class<? extends Entity>)LOTREntityUrukHaiBannerBearer.class, "UrukHaiBannerBearer", 107, 2369050, 5790015);
        registerCreature((Class<? extends Entity>)LOTREntityDwarfBannerBearer.class, "DwarfBannerBearer", 108, 2238506, 7108730);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarBannerBearer.class, "AngmarBannerBearer", 109, 3224873, 5601097);
        registerCreature((Class<? extends Entity>)LOTREntityNearHaradBannerBearer.class, "NearHaradBannerBearer", 110, 2171169, 11868955);
        registerCreature((Class<? extends Entity>)LOTREntityHighElfBannerBearer.class, "HighElfBannerBearer", 111, 14935016, 7040410);
        registerCreature((Class<? extends Entity>)LOTREntityJungleScorpion.class, "JungleScorpion", 112, 2630945, 1315088);
        registerCreature((Class<? extends Entity>)LOTREntityDesertScorpion.class, "DesertScorpion", 113, 16376764, 11772801);
        registerCreature((Class<? extends Entity>)LOTREntityBird.class, "Bird", 114, 7451872, 7451872);
        registerCreature((Class<? extends Entity>)LOTREntityCrebain.class, "Crebain", 115, 2434341, 10490368);
        registerCreature((Class<? extends Entity>)LOTREntityCamel.class, "Camel", 116, 13150061, 9203768);
        registerCreature((Class<? extends Entity>)LOTREntityNearHaradrimArcher.class, "NearHaradrimArcher", 117, 2171169, 11868955);
        registerCreature((Class<? extends Entity>)LOTREntityNearHaradrimWarlord.class, "NearHaradrimWarlord", 118, 2171169, 11868955);
        registerCreature((Class<? extends Entity>)LOTREntityBlueDwarf.class, "BlueDwarf", 119, 16353133, 15357472);
        registerCreature((Class<? extends Entity>)LOTREntityBlueDwarfWarrior.class, "BlueDwarfWarrior", 120, 3161673, 6257551);
        registerCreature((Class<? extends Entity>)LOTREntityBlueDwarfAxeThrower.class, "BlueDwarfAxeThrower", 121, 3161673, 6257551);
        registerCreature((Class<? extends Entity>)LOTREntityBlueDwarfBannerBearer.class, "BlueDwarfBannerBearer", 122, 3161673, 6257551);
        registerCreature((Class<? extends Entity>)LOTREntityBlueDwarfCommander.class, "BlueDwarfCommander", 123, 3161673, 6257551);
        registerCreature((Class<? extends Entity>)LOTREntityBlueDwarfMiner.class, "BlueDwarfMiner", 124, 16353133, 15357472);
        registerCreature((Class<? extends Entity>)LOTREntitySouthronBrewer.class, "NearHaradDrinksTrader", 125, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntitySouthronMiner.class, "NearHaradMineralsTrader", 126, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntitySouthronFlorist.class, "NearHaradPlantsTrader", 127, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntitySouthronButcher.class, "NearHaradFoodTrader", 128, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityBlueDwarfMerchant.class, "BlueDwarfMerchant", 129, 16353133, 15357472);
        registerCreature((Class<? extends Entity>)LOTREntityBandit.class, "Bandit", 130, 16225652, 5323553);
        registerCreature((Class<? extends Entity>)LOTREntityRangerNorthBannerBearer.class, "RangerNorthBannerBearer", 131, 4473912, 2302748);
        registerCreature((Class<? extends Entity>)LOTREntityElk.class, "Elk", 132, 15459801, 11905424);
        registerCreature((Class<? extends Entity>)LOTREntityGondorTowerGuard.class, "GondorTowerGuard", 133, 5327948, 15063770);
        registerCreature((Class<? extends Entity>)LOTREntityNearHaradMerchant.class, "NearHaradMerchant", 134, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityHaradPyramidWraith.class, "HaradPyramidWraith", 135, 10854007, 15590575);
        registerCreature((Class<? extends Entity>)LOTREntityDolGuldurOrc.class, "DolGuldurOrc", 136, 4408654, 2040101);
        registerCreature((Class<? extends Entity>)LOTREntityDolGuldurOrcArcher.class, "DolGuldurOrcArcher", 137, 4408654, 2040101);
        registerCreature((Class<? extends Entity>)LOTREntityDolGuldurBannerBearer.class, "DolGuldurBannerBearer", 138, 4408654, 2040101);
        registerCreature((Class<? extends Entity>)LOTREntityDolGuldurOrcChieftain.class, "DolGuldurChieftain", 139, 4408654, 2040101);
        registerCreature((Class<? extends Entity>)LOTREntityMirkTroll.class, "MirkTroll", 140, 4408654, 2040101);
        registerCreature((Class<? extends Entity>)LOTREntityGundabadBannerBearer.class, "GundabadBannerBearer", 141, 3352346, 8548435);
        registerCreature((Class<? extends Entity>)LOTREntityTermite.class, "Termite", 142, 1512461, 3091236);
        registerCreature((Class<? extends Entity>)LOTREntityDikDik.class, "DikDik", 143, 12023867, 6833961);
        registerCreature((Class<? extends Entity>)LOTREntityBlackUruk.class, "BlackUruk", 144, 988430, 2830632);
        registerCreature((Class<? extends Entity>)LOTREntityBlackUrukArcher.class, "BlackUrukArcher", 145, 988430, 2830632);
        registerCreature((Class<? extends Entity>)LOTREntityHalfTroll.class, "HalfTroll", 146, 6903359, 3614236);
        registerCreature((Class<? extends Entity>)LOTREntityRangerIthilienCaptain.class, "RangerIthilienCaptain", 147, 4015141, 1382669);
        registerCreature((Class<? extends Entity>)LOTREntityRangerIthilienBannerBearer.class, "RangerIthilienBannerBearer", 148, 4015141, 1382669);
        registerCreature((Class<? extends Entity>)LOTREntityHalfTrollWarrior.class, "HalfTrollWarrior", 149, 9403002, 6244662);
        registerCreature((Class<? extends Entity>)LOTREntityHalfTrollBannerBearer.class, "HalfTrollBannerBearer", 150, 9403002, 6244662);
        registerCreature((Class<? extends Entity>)LOTREntityHalfTrollWarlord.class, "HalfTrollWarlord", 151, 9403002, 6244662);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarOrcTrader.class, "AngmarOrcTrader", 152, 5979436, 13421772);
        registerCreature((Class<? extends Entity>)LOTREntityDolGuldurOrcTrader.class, "DolGuldurOrcTrader", 153, 4408654, 2040101);
        registerCreature((Class<? extends Entity>)LOTREntityHalfTrollScavenger.class, "HalfTrollScavenger", 154, 6903359, 3614236);
        registerCreature((Class<? extends Entity>)LOTREntityGaladhrimSmith.class, "GaladhrimSmith", 155, 9337185, 15920555);
        registerCreature((Class<? extends Entity>)LOTREntityHighElfSmith.class, "HighElfSmith", 156, 16761223, 15721387);
        registerCreature((Class<? extends Entity>)LOTREntityWoodElfSmith.class, "WoodElfSmith", 157, 2314529, 16764574);
        registerCreature((Class<? extends Entity>)LOTREntitySwanKnight.class, "SwanKnight", 158, 2302535, 15918822);
        registerCreature((Class<? extends Entity>)LOTREntityDolAmrothCaptain.class, "DolAmrothCaptain", 159, 2302535, 15918822);
        registerCreature((Class<? extends Entity>)LOTREntityDolAmrothBannerBearer.class, "DolAmrothBannerBearer", 160, 3227005, 14278898);
        registerCreature((Class<? extends Entity>)LOTREntitySwan.class, "Swan", 161, 16119285, 15571785);
        registerCreature((Class<? extends Entity>)LOTREntityMoredain.class, "Moredain", 162, 5323303, 2168848);
        registerCreature((Class<? extends Entity>)LOTREntityMoredainWarrior.class, "MoredainWarrior", 163, 8998697, 5057302);
        registerCreature((Class<? extends Entity>)LOTREntityMoredainBannerBearer.class, "MoredainBannerBearer", 164, 8998697, 5057302);
        registerCreature((Class<? extends Entity>)LOTREntityMoredainChieftain.class, "MoredainChieftain", 165, 13807978, 11166513);
        registerCreature((Class<? extends Entity>)LOTREntityMoredainHuntsman.class, "MoredainHuntsman", 166, 5323303, 2168848);
        registerCreature((Class<? extends Entity>)LOTREntityMoredainHutmaker.class, "MoredainHutmaker", 167, 5323303, 2168848);
        registerCreature((Class<? extends Entity>)LOTREntityDunlendingBerserker.class, "DunlendingBerserker", 168, 5192753, 16050121);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarHillman.class, "AngmarHillman", 169, 11828586, 2891544);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarHillmanWarrior.class, "AngmarHillmanWarrior", 170, 11828586, 2891544);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarHillmanChieftain.class, "AngmarHillmanChieftain", 171, 11828586, 2891544);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarHillmanBannerBearer.class, "AngmarHillmanBannerBearer", 172, 11828586, 2891544);
        registerCreature((Class<? extends Entity>)LOTREntityAngmarHillmanAxeThrower.class, "AngmarHillmanAxeThrower", 173, 11828586, 2891544);
        registerCreature((Class<? extends Entity>)LOTREntityDunlendingAxeThrower.class, "DunlendingAxeThrower", 174, 5192753, 9337975);
        registerCreature((Class<? extends Entity>)LOTREntityIronHillsMerchant.class, "IronHillsMerchant", 175, 16353133, 15357472);
        registerCreature((Class<? extends Entity>)LOTREntityMallornEnt.class, "MallornEnt", 176);
        registerCreature((Class<? extends Entity>)LOTREntityScrapTrader.class, "ScrapTrader", 177, 16225652, 5323553);
        registerCreature((Class<? extends Entity>)LOTREntityTauredain.class, "Tauredain", 178, 4468770, 12948008);
        registerCreature((Class<? extends Entity>)LOTREntityTauredainWarrior.class, "TauredainWarrior", 179, 5652267, 9165389);
        registerCreature((Class<? extends Entity>)LOTREntityTauredainBannerBearer.class, "TauredainBannerBearer", 180, 5652267, 9165389);
        registerCreature((Class<? extends Entity>)LOTREntityTauredainChieftain.class, "TauredainChieftain", 181, 5652267, 9165389);
        registerCreature((Class<? extends Entity>)LOTREntityTauredainBlowgunner.class, "TauredainBlowgunner", 182, 5652267, 9165389);
        registerCreature((Class<? extends Entity>)LOTREntityBarrowWight.class, "BarrowWight", 183, 529926, 3111505);
        registerCreature((Class<? extends Entity>)LOTREntityTauredainShaman.class, "TauredainShaman", 184, 4468770, 12948008);
        registerCreature((Class<? extends Entity>)LOTREntityGaladhrimWarden.class, "GaladhrimWarden", 185, 10527645, 8027255);
        registerCreature((Class<? extends Entity>)LOTREntityTauredainFarmer.class, "TauredainFarmer", 186, 4468770, 12948008);
        registerCreature((Class<? extends Entity>)LOTREntityTauredainFarmhand.class, "TauredainFarmhand", 187, 4468770, 12948008);
        registerCreature((Class<? extends Entity>)LOTREntityDwarfSmith.class, "DwarfSmith", 188, 16353133, 15357472);
        registerCreature((Class<? extends Entity>)LOTREntityBlueMountainsSmith.class, "BlueDwarfSmith", 189, 16353133, 15357472);
        registerCreature((Class<? extends Entity>)LOTREntityTauredainPyramidWraith.class, "TauredainPyramidWraith", 190, 12698049, 4802889);
        registerCreature((Class<? extends Entity>)LOTREntityGundabadUruk.class, "GundabadUruk", 191, 2563350, 6382678);
        registerCreature((Class<? extends Entity>)LOTREntityGundabadUrukArcher.class, "GundabadUrukArcher", 192, 2563350, 6382678);
        registerCreature((Class<? extends Entity>)LOTREntityIsengardSnaga.class, "IsengardSnaga", 193, 4339500, 8352349);
        registerCreature((Class<? extends Entity>)LOTREntityIsengardSnagaArcher.class, "IsengardSnagaArcher", 194, 4339500, 8352349);
        registerCreature((Class<? extends Entity>)LOTREntityBanditHarad.class, "BanditHarad", 195, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityDeer.class, "Deer", 196, 5978669, 11968394);
        registerCreature((Class<? extends Entity>)LOTREntityDaleMan.class, "DaleMan", 197, 16755851, 5252113);
        registerCreature((Class<? extends Entity>)LOTREntityDaleLevyman.class, "DaleLevyman", 198, 7034184, 5252113);
        registerCreature((Class<? extends Entity>)LOTREntityDaleSoldier.class, "DaleSoldier", 199, 11776947, 481419);
        registerCreature((Class<? extends Entity>)LOTREntityDaleArcher.class, "DaleArcher", 200, 11776947, 481419);
        registerCreature((Class<? extends Entity>)LOTREntityDaleBannerBearer.class, "DaleBannerBearer", 201, 11776947, 481419);
        registerCreature((Class<? extends Entity>)LOTREntityDaleCaptain.class, "DaleCaptain", 202, 11776947, 481419);
        registerCreature((Class<? extends Entity>)LOTREntityDaleBlacksmith.class, "DaleBlacksmith", 203, 16755851, 5252113);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionMan.class, "DorwinionMan", 204, 16755851, 12213157);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionGuard.class, "DorwinionGuard", 205, 9005901, 6178167);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionCaptain.class, "DorwinionCaptain", 206, 9005901, 6178167);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionBannerBearer.class, "DorwinionBannerBearer", 207, 9005901, 6178167);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionElf.class, "DorwinionElf", 208, 16761223, 8538746);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionElfWarrior.class, "DorwinionElfWarrior", 209, 13420999, 8407696);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionElfBannerBearer.class, "DorwinionElfBannerBearer", 210, 13420999, 8407696);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionElfCaptain.class, "DorwinionElfCaptain", 211, 13420999, 8407696);
        registerCreature((Class<? extends Entity>)LOTREntityDaleBaker.class, "DaleBaker", 212, 16755851, 5252113);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionElfVintner.class, "DorwinionElfVintner", 213, 9721246, 5648736);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionVinehand.class, "DorwinionVinehand", 214, 16755851, 12213157);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionVinekeeper.class, "DorwinionVinekeeper", 215, 16755851, 12213157);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionMerchantElf.class, "DorwinionMerchant", 216, 16761223, 8538746);
        registerCreature((Class<? extends Entity>)LOTREntityDaleMerchant.class, "DaleMerchant", 217, 16755851, 5252113);
        registerCreature((Class<? extends Entity>)LOTREntityAurochs.class, "Aurochs", 218, 7488812, 3217935);
        registerCreature((Class<? extends Entity>)LOTREntityKineAraw.class, "KineAraw", 219, 16702665, 12890019);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionCrossbower.class, "DorwinionCrossbower", 220, 9005901, 6178167);
        registerCreature((Class<? extends Entity>)LOTREntityLossarnachAxeman.class, "LossarnachAxeman", 221, 11578026, 3812901);
        registerCreature((Class<? extends Entity>)LOTREntityLossarnachBannerBearer.class, "LossarnachBannerBearer", 222, 11578026, 3812901);
        registerCreature((Class<? extends Entity>)LOTREntityBlackUrukBannerBearer.class, "BlackUrukBannerBearer", 223, 988430, 2830632);
        registerCreature((Class<? extends Entity>)LOTREntityPelargirMarine.class, "PelargirMarine", 224, 13090494, 1475447);
        registerCreature((Class<? extends Entity>)LOTREntityPelargirBannerBearer.class, "PelargirBannerBearer", 225, 13090494, 1475447);
        registerCreature((Class<? extends Entity>)LOTREntityPinnathGelinSoldier.class, "PinnathGelinSoldier", 226, 11183011, 29235);
        registerCreature((Class<? extends Entity>)LOTREntityPinnathGelinBannerBearer.class, "PinnathGelinBannerBearer", 227, 11183011, 29235);
        registerCreature((Class<? extends Entity>)LOTREntityBlackrootSoldier.class, "BlackrootSoldier", 228, 11183011, 3881016);
        registerCreature((Class<? extends Entity>)LOTREntityBlackrootBannerBearer.class, "BlackrootBannerBearer", 229, 11183011, 3881016);
        registerCreature((Class<? extends Entity>)LOTREntityBlackrootArcher.class, "BlackrootArcher", 230, 11183011, 3881016);
        registerCreature((Class<? extends Entity>)LOTREntityGondorLevyman.class, "GondorLevyman", 231, 10789794, 6833716);
        registerCreature((Class<? extends Entity>)LOTREntityNanUngolBannerBearer.class, "NanUngolBannerBearer", 232, 3353378, 7042407);
        registerCreature((Class<? extends Entity>)LOTREntityMinasMorgulBannerBearer.class, "MinasMorgulBannerBearer", 233, 3353378, 7042407);
        registerCreature((Class<? extends Entity>)LOTREntityDolAmrothSoldier.class, "DolAmrothSoldier", 234, 3227005, 14278898);
        registerCreature((Class<? extends Entity>)LOTREntityDolAmrothArcher.class, "DolAmrothArcher", 235, 3227005, 14278898);
        registerCreature((Class<? extends Entity>)LOTREntityGondorFarmer.class, "GondorFarmer", 236, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityGondorFarmhand.class, "GondorFarmhand", 237, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityLebenninLevyman.class, "LebenninLevyman", 238, 14866637, 3573666);
        registerCreature((Class<? extends Entity>)LOTREntityLebenninBannerBearer.class, "LebenninBannerBearer", 239, 14866637, 3573666);
        registerCreature((Class<? extends Entity>)LOTREntityGondorBartender.class, "GondorBartender", 240, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityGondorGreengrocer.class, "GondorGreengrocer", 241, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityGondorLumberman.class, "GondorLumberman", 242, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityGondorMason.class, "GondorMason", 243, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityGondorBrewer.class, "GondorBrewer", 244, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityGondorFlorist.class, "GondorFlorist", 245, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityGondorButcher.class, "GondorButcher", 246, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityGondorFishmonger.class, "GondorFishmonger", 247, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityGondorBaker.class, "GondorBaker", 248, 13547685, 5652538);
        registerCreature((Class<? extends Entity>)LOTREntityLossarnachCaptain.class, "LossarnachCaptain", 249, 11578026, 3812901);
        registerCreature((Class<? extends Entity>)LOTREntityPelargirCaptain.class, "PelargirCaptain", 250, 13090494, 1475447);
        registerCreature((Class<? extends Entity>)LOTREntityPinnathGelinCaptain.class, "PinnathGelinCaptain", 251, 11183011, 29235);
        registerCreature((Class<? extends Entity>)LOTREntityBlackrootCaptain.class, "BlackrootCaptain", 252, 11183011, 3881016);
        registerCreature((Class<? extends Entity>)LOTREntityLebenninCaptain.class, "LebenninCaptain", 253, 5327948, 15063770);
        registerCreature((Class<? extends Entity>)LOTREntityLamedonSoldier.class, "LamedonSoldier", 254, 12103600, 3624035);
        registerCreature((Class<? extends Entity>)LOTREntityLamedonArcher.class, "LamedonArcher", 255, 12103600, 3624035);
        registerCreature((Class<? extends Entity>)LOTREntityLamedonBannerBearer.class, "LamedonBannerBearer", 256, 12103600, 3624035);
        registerCreature((Class<? extends Entity>)LOTREntityLamedonCaptain.class, "LamedonCaptain", 257, 12103600, 3624035);
        registerCreature((Class<? extends Entity>)LOTREntityLamedonHillman.class, "LamedonHillman", 258, 13547685, 2108991);
        registerCreature((Class<? extends Entity>)LOTREntityRohanFarmhand.class, "RohanFarmhand", 259, 16424833, 13406801);
        registerCreature((Class<? extends Entity>)LOTREntityGorcrow.class, "Gorcrow", 260, 928034, 5451403);
        registerCreature((Class<? extends Entity>)LOTREntitySeagull.class, "Seagull", 261, 15920107, 13997863);
        registerCreature((Class<? extends Entity>)LOTREntityRohanFarmer.class, "RohanFarmer", 262, 16424833, 13406801);
        registerCreature((Class<? extends Entity>)LOTREntityRohanLumberman.class, "RohanLumberman", 263, 16424833, 13406801);
        registerCreature((Class<? extends Entity>)LOTREntityRohanBuilder.class, "RohanBuilder", 264, 16424833, 13406801);
        registerCreature((Class<? extends Entity>)LOTREntityRohanBrewer.class, "RohanBrewer", 265, 16424833, 13406801);
        registerCreature((Class<? extends Entity>)LOTREntityRohanButcher.class, "RohanButcher", 266, 16424833, 13406801);
        registerCreature((Class<? extends Entity>)LOTREntityRohanFishmonger.class, "RohanFishmonger", 267, 16424833, 13406801);
        registerCreature((Class<? extends Entity>)LOTREntityRohanBaker.class, "RohanBaker", 268, 16424833, 13406801);
        registerCreature((Class<? extends Entity>)LOTREntityRohanOrcharder.class, "RohanOrcharder", 269, 16424833, 13406801);
        registerCreature((Class<? extends Entity>)LOTREntityDunedainBlacksmith.class, "DunedainBlacksmith", 270, 15638664, 6832694);
        registerCreature((Class<? extends Entity>)LOTREntityRohanStablemaster.class, "RohanStablemaster", 271, 16424833, 13406801);
        registerCreature((Class<? extends Entity>)LOTREntityBear.class, "Bear", 272, 7492416, 4008994);
        registerCreature((Class<? extends Entity>)LOTREntityEasterling.class, "Easterling", 273, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingWarrior.class, "EasterlingWarrior", 274, 7486267, 15251832);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingBannerBearer.class, "EasterlingBannerBearer", 275, 7486267, 15251832);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingArcher.class, "EasterlingArcher", 276, 7486267, 15251832);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingBlacksmith.class, "EasterlingBlacksmith", 277, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingWarlord.class, "EasterlingWarlord", 278, 14265689, 12004653);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingFireThrower.class, "EasterlingFireThrower", 279, 7486267, 15251832);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingLevyman.class, "EasterlingLevyman", 280, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionMerchantMan.class, "DorwinionMerchantMan", 281, 16755851, 12213157);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingGoldWarrior.class, "EasterlingGoldWarrior", 282, 14265689, 12004653);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingLumberman.class, "EasterlingLumberman", 283, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingMason.class, "EasterlingMason", 284, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingButcher.class, "EasterlingButcher", 285, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingBrewer.class, "EasterlingBrewer", 286, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingFishmonger.class, "EasterlingFishmonger", 287, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingBaker.class, "EasterlingBaker", 288, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingHunter.class, "EasterlingHunter", 289, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingFarmer.class, "EasterlingFarmer", 290, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingGoldsmith.class, "EasterlingGoldsmith", 291, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingBartender.class, "EasterlingBartender", 292, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityDorwinionElfArcher.class, "DorwinionElfArcher", 293, 13420999, 8407696);
        registerCreature((Class<? extends Entity>)LOTREntityEasterlingFarmhand.class, "EasterlingFarmhand", 294, 16093531, 6176050);
        registerCreature((Class<? extends Entity>)LOTREntityRivendellElf.class, "RivendellElf", 295, 16761223, 15721387);
        registerCreature((Class<? extends Entity>)LOTREntityRivendellWarrior.class, "RivendellWarrior", 296, 14738662, 10723248);
        registerCreature((Class<? extends Entity>)LOTREntityRivendellLord.class, "RivendellLord", 297, 14738662, 10723248);
        registerCreature((Class<? extends Entity>)LOTREntityRivendellBannerBearer.class, "RivendellBannerBearer", 298, 14738662, 10723248);
        registerCreature((Class<? extends Entity>)LOTREntityRivendellSmith.class, "RivendellSmith", 299, 16761223, 15721387);
        registerCreature((Class<? extends Entity>)LOTREntityEsgarothBannerBearer.class, "EsgarothBannerBearer", 300, 11776947, 481419);
        registerCreature((Class<? extends Entity>)LOTREntityRivendellTrader.class, "RivendellTrader", 301, 869480, 15003391);
        registerCreature((Class<? extends Entity>)LOTREntityFish.class, "Fish", 302, 7053203, 11913189);
        registerCreature((Class<? extends Entity>)LOTREntityGundabadOrcTrader.class, "GundabadOrcTrader", 303, 5979436, 13421772);
        registerCreature((Class<? extends Entity>)LOTREntityNearHaradBlacksmith.class, "NearHaradBlacksmith", 304, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntitySnowTroll.class, "SnowTroll", 305, 14606046, 11059905);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedhrim.class, "Harnedhrim", 306, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorWarrior.class, "HarnedorWarrior", 307, 7016721, 14852422);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorArcher.class, "HarnedorArcher", 308, 7016721, 14852422);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorBannerBearer.class, "HarnedorBannerBearer", 309, 7016721, 14852422);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarian.class, "Umbarian", 310, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarWarrior.class, "UmbarWarrior", 311, 2960680, 13540692);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarArcher.class, "UmbarArcher", 312, 2960680, 13540692);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarBannerBearer.class, "UmbarBannerBearer", 313, 2960680, 13540692);
        registerCreature((Class<? extends Entity>)LOTREntityMoredainMercenary.class, "MoredainMercenary", 314, 8998697, 14528351);
        registerCreature((Class<? extends Entity>)LOTREntityGulfHaradrim.class, "GulfHaradrim", 315, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityGulfHaradWarrior.class, "GulfWarrior", 316, 7478299, 12827550);
        registerCreature((Class<? extends Entity>)LOTREntityGulfHaradArcher.class, "GulfArcher", 317, 7478299, 12827550);
        registerCreature((Class<? extends Entity>)LOTREntityGulfHaradBannerBearer.class, "GulfBannerBearer", 318, 7478299, 12827550);
        registerCreature((Class<? extends Entity>)LOTREntityCorsair.class, "Corsair", 319, 5521973, 12813617);
        registerCreature((Class<? extends Entity>)LOTREntityNomad.class, "Nomad", 320, 8278064, 853765);
        registerCreature((Class<? extends Entity>)LOTREntityNomadWarrior.class, "NomadWarrior", 321, 10063441, 5658198);
        registerCreature((Class<? extends Entity>)LOTREntityNomadArcher.class, "NomadArcher", 322, 10063441, 5658198);
        registerCreature((Class<? extends Entity>)LOTREntityNomadBannerBearer.class, "NomadBannerBearer", 323, 10063441, 5658198);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorWarlord.class, "HarnedorWarlord", 324, 7016721, 14852422);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarCaptain.class, "UmbarCaptain", 325, 2960680, 13540692);
        registerCreature((Class<? extends Entity>)LOTREntityCorsairCaptain.class, "CorsairCaptain", 326, 5521973, 12813617);
        registerCreature((Class<? extends Entity>)LOTREntityNomadChieftain.class, "NomadChieftain", 327, 10063441, 5658198);
        registerCreature((Class<? extends Entity>)LOTREntityGulfHaradWarlord.class, "GulfWarlord", 328, 7478299, 12827550);
        registerCreature((Class<? extends Entity>)LOTREntitySouthronChampion.class, "SouthronChampion", 329, 2171169, 11868955);
        registerCreature((Class<? extends Entity>)LOTREntityHaradSlave.class, "HaradSlave", 330, 9860177, 5579298);
        registerCreature((Class<? extends Entity>)LOTREntityCorsairSlaver.class, "CorsairSlaver", 331, 5521973, 12813617);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorBlacksmith.class, "HarnedorBlacksmith", 332, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarBlacksmith.class, "UmbarBlacksmith", 333, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityGulfBlacksmith.class, "GulfBlacksmith", 334, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityGondorRenegade.class, "GondorRenegade", 335, 1776411, 13936679);
        registerCreature((Class<? extends Entity>)LOTREntityNomadMerchant.class, "NomadMerchant", 336, 13551017, 7825215);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorBartender.class, "HarnedorBartender", 337, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorLumberman.class, "HarnedorLumberman", 338, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorMason.class, "HarnedorMason", 339, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorButcher.class, "HarnedorButcher", 340, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorBrewer.class, "HarnedorBrewer", 341, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorFishmonger.class, "HarnedorFishmonger", 342, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorBaker.class, "HarnedorBaker", 343, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorHunter.class, "HarnedorHunter", 344, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorMiner.class, "HarnedorMiner", 345, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntitySouthronLumberman.class, "SouthronLumberman", 346, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntitySouthronMason.class, "SouthronMason", 347, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntitySouthronFishmonger.class, "SouthronFishmonger", 348, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntitySouthronBaker.class, "SouthronBaker", 349, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntitySouthronGoldsmith.class, "SouthronGoldsmith", 350, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarLumberman.class, "UmbarLumberman", 351, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarButcher.class, "UmbarButcher", 352, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarBrewer.class, "UmbarBrewer", 353, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarFishmonger.class, "UmbarFishmonger", 354, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarBaker.class, "UmbarBaker", 355, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarFlorist.class, "UmbarFlorist", 356, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarMiner.class, "UmbarMiner", 357, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarGoldsmith.class, "UmbarGoldsmith", 358, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarMason.class, "UmbarMason", 359, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityNomadMason.class, "NomadMason", 360, 8278064, 853765);
        registerCreature((Class<? extends Entity>)LOTREntityNomadBrewer.class, "NomadBrewer", 361, 8278064, 853765);
        registerCreature((Class<? extends Entity>)LOTREntityNomadMiner.class, "NomadMiner", 362, 8278064, 853765);
        registerCreature((Class<? extends Entity>)LOTREntityGulfMason.class, "GulfMason", 363, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityGulfButcher.class, "GulfButcher", 364, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityGulfBrewer.class, "GulfBrewer", 365, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityGulfFishmonger.class, "GulfFishmonger", 366, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityGulfBaker.class, "GulfBaker", 367, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityGulfMiner.class, "GulfMiner", 368, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityGulfGoldsmith.class, "GulfGoldsmith", 369, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityGulfLumberman.class, "GulfLumberman", 370, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityGulfHunter.class, "GulfHunter", 371, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityNomadArmourer.class, "NomadArmourer", 372, 8278064, 853765);
        registerCreature((Class<? extends Entity>)LOTREntitySouthronBartender.class, "SouthronBartender", 373, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarBartender.class, "UmbarBartender", 374, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityGulfBartender.class, "GulfBartender", 375, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorFarmhand.class, "HarnedorFarmhand", 376, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityHarnedorFarmer.class, "HarnedorFarmer", 377, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntitySouthronFarmer.class, "SouthronFarmer", 378, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityUmbarFarmer.class, "UmbarFarmer", 379, 10779229, 2960685);
        registerCreature((Class<? extends Entity>)LOTREntityGulfFarmer.class, "GulfFarmer", 380, 9854777, 1181187);
        registerCreature((Class<? extends Entity>)LOTREntityTauredainSmith.class, "TauredainSmith", 381, 4468770, 12948008);
        registerCreature((Class<? extends Entity>)LOTREntityWhiteOryx.class, "WhiteOryx", 382, 16381146, 8154724);
        registerCreature((Class<? extends Entity>)LOTREntityBlackUrukCaptain.class, "BlackUrukCaptain", 383, 988430, 2830632);
        registerCreature((Class<? extends Entity>)LOTREntityWickedDwarf.class, "WickedDwarf", 384, 14516076, 8869453);
        registerCreature((Class<? extends Entity>)LOTREntityUtumnoOrc.class, "UtumnoOrc", 800, 2694951, 10377233);
        registerCreature((Class<? extends Entity>)LOTREntityUtumnoOrcArcher.class, "UtumnoOrcArcher", 801, 2694951, 10377233);
        registerCreature((Class<? extends Entity>)LOTREntityUtumnoWarg.class, "UtumnoWarg", 802, 4600617, 2694422);
        registerCreature((Class<? extends Entity>)LOTREntityUtumnoIceWarg.class, "UtumnoIceWarg", 803, 15066080, 9348269);
        registerCreature((Class<? extends Entity>)LOTREntityUtumnoObsidianWarg.class, "UtumnoObsidianWarg", 804, 2960169, 1644310);
        registerCreature((Class<? extends Entity>)LOTREntityUtumnoFireWarg.class, "UtumnoFireWarg", 805, 6958364, 13530368);
        registerCreature((Class<? extends Entity>)LOTREntityUtumnoIceSpider.class, "UtumnoIceSpider", 806, 15594495, 7697919);
        registerCreature((Class<? extends Entity>)LOTREntityBalrog.class, "Balrog", 807, 1772037, 13009920);
        registerCreature((Class<? extends Entity>)LOTREntityTormentedElf.class, "TormentedElf", 808, 14079919, 4337710);
        registerCreature((Class<? extends Entity>)LOTREntityUtumnoTroll.class, "UtumnoTroll", 809, 10580563, 7422265);
        registerCreature((Class<? extends Entity>)LOTREntityUtumnoSnowTroll.class, "UtumnoSnowTroll", 810, 14606046, 11059905);
        registerCreature((Class<? extends Entity>)LOTREntityGollum.class, "Gollum", 1001, 13417872, 9471333);
        registerCreature((Class<? extends Entity>)LOTREntitySaruman.class, "Saruman", 1002, 15132390, 11776947);
        registerCreature((Class<? extends Entity>)LOTREntityGandalf.class, "Gandalf", 1003, 9605778, 5923198);
        registerEntity(LOTREntityPortal.class, "Portal", 2000, 80, 3, true);
        registerEntity((Class<? extends Entity>)LOTREntitySmokeRing.class, "SmokeRing", 2001, 64, 10, true);
        registerEntity((Class<? extends Entity>)LOTREntityOrcBomb.class, "OrcBomb", 2002, 160, 10, true);
        registerEntity((Class<? extends Entity>)LOTREntityGandalfFireball.class, "GandalfFireball", 2003, 64, 10, true);
        registerEntity(LOTREntitySpear.class, "Spear", 2004, 64, Integer.MAX_VALUE, false);
        registerEntity((Class<? extends Entity>)LOTREntityPlate.class, "Plate", 2005, 64, 3, true);
        registerEntity(LOTREntityWargskinRug.class, "WargRug", 2006, 80, 3, true);
        registerEntity((Class<? extends Entity>)LOTREntityMarshWraithBall.class, "MarshWraithBall", 2007, 64, 10, true);
        registerEntity(LOTREntityThrowingAxe.class, "ThrowingAxe", 2008, 64, Integer.MAX_VALUE, false);
        registerEntity(LOTREntityCrossbowBolt.class, "CrossbowBolt", 2009, 64, Integer.MAX_VALUE, false);
        registerEntity(LOTREntityStoneTroll.class, "StoneTroll", 2010, 80, 3, true);
        registerEntity((Class<? extends Entity>)LOTREntityPebble.class, "Pebble", 2011, 64, 3, true);
        registerEntity((Class<? extends Entity>)LOTREntityMysteryWeb.class, "MysteryWeb", 2012, 64, 10, true);
        registerEntity(LOTREntityTraderRespawn.class, "TraderRespawn", 2013, 80, 3, true);
        registerEntity((Class<? extends Entity>)LOTREntityThrownRock.class, "ThrownRock", 2014, 64, 10, true);
        registerEntity(LOTREntityBarrel.class, "Barrel", 2015, 80, 3, true);
        registerEntity(LOTREntityBanner.class, "Banner", 2016, 160, 3, true);
        registerEntity((Class<? extends Entity>)LOTREntityBannerWall.class, "WallBanner", 2017, 160, Integer.MAX_VALUE, false);
        registerEntity(LOTREntityInvasionSpawner.class, "InvasionSpawner", 2018, 80, 3, true);
        registerEntity((Class<? extends Entity>)LOTREntityThrownTermite.class, "ThrownTermite", 2019, 64, 10, true);
        registerEntity((Class<? extends Entity>)LOTREntityConker.class, "Conker", 2020, 64, 3, true);
        registerEntity(LOTREntityBossTrophy.class, "BossTrophy", 2022, 80, 3, true);
        registerEntity((Class<? extends Entity>)LOTREntityMallornLeafBomb.class, "MallornLeafBomb", 2023, 64, 10, true);
        registerEntity((Class<? extends Entity>)LOTREntityFishHook.class, "LOTRFishHook", 2024, 64, 5, true);
        registerEntity(LOTREntityDart.class, "Dart", 2025, 64, Integer.MAX_VALUE, false);
        registerEntity(LOTREntityNPCRespawner.class, "NPCRespawner", 2027, 80, 3, true);
        registerEntity(LOTREntityFallingTreasure.class, "FallingTreasure", 2028, 160, 20, true);
        registerEntity((Class<? extends Entity>)LOTREntityFallingFireJar.class, "FallingFireJar", 2029, 160, 20, true);
        registerEntity((Class<? extends Entity>)LOTREntityFirePot.class, "ThrownFirePot", 2030, 64, 3, true);
        registerEntity((Class<? extends Entity>)LOTREntityArrowPoisoned.class, "ArrowPoison", 2031, 64, 20, false);
        registerEntity((Class<? extends Entity>)LOTREntityTrollSnowball.class, "TrollSnowball", 2032, 64, 10, true);
        registerEntity(LOTREntityLionRug.class, "LionRug", 2033, 80, 3, true);
        registerEntity(LOTREntityBearRug.class, "BearRug", 2034, 80, 3, true);
        registerEntity(LOTREntityGiraffeRug.class, "GiraffeRug", 2035, 80, 3, true);
    }
    
    public static int getEntityID(final Entity entity) {
        return getEntityIDFromClass(entity.getClass());
    }
    
    public static int getEntityIDFromClass(final Class entityClass) {
        return LOTREntities.classToIDMapping.get(entityClass);
    }
    
    public static String getStringFromClass(final Class entityClass) {
        return EntityList.classToStringMapping.get(entityClass);
    }
    
    public static int getIDFromString(final String name) {
        if (!LOTREntities.stringToIDMapping.containsKey(name)) {
            return 0;
        }
        return LOTREntities.stringToIDMapping.get(name);
    }
    
    public static Class<? extends Entity> getClassFromString(final String name) {
        return EntityList.stringToClassMapping.get(name);
    }
    
    public static String getStringFromID(final int id) {
        return LOTREntities.IDToStringMapping.get(id);
    }
    
    public static Entity createEntityByClass(final Class entityClass, final World world) {
        Entity entity = null;
        try {
            entity = entityClass.getConstructor(World.class).newInstance(world);
        }
        catch (Exception exception) {
            exception.printStackTrace();
        }
        return entity;
    }
    
    public static Set<String> getAllEntityNames() {
        return Collections.unmodifiableSet((Set<? extends String>)LOTREntities.stringToIDMapping.keySet());
    }
    
    static {
        LOTREntities.spawnEggs = new LinkedHashMap<Integer, SpawnEggInfo>();
        LOTREntities.stringToIDMapping = new HashMap<String, Integer>();
        LOTREntities.IDToStringMapping = new HashMap<Integer, String>();
        LOTREntities.classToIDMapping = new HashMap<Class<? extends Entity>, Integer>();
    }
    
    public static class SpawnEggInfo
    {
        public final int spawnedID;
        public final int primaryColor;
        public final int secondaryColor;
        
        public SpawnEggInfo(final int i, final int j, final int k) {
            this.spawnedID = i;
            this.primaryColor = j;
            this.secondaryColor = k;
        }
    }
}
